### ISSUE TITLE
Option not to print plots, but to return the plot object

### ISSUE THREAD

**Issue by jmberros** [rsquaredacademy/olsrr#135]
It would be useful to have an option to return ggplot objects instead of printing them, in the plot methods. This would allow to arrange the plots in a custom layout using `grid.Extra` or to modify some of the plot elements before printing them.

For instance `ols_plot_resid_qq` could [end](https://github.com/rsquaredacademy/olsrr/blob/master/R/ols-residual-qqplot.R#L36) in a `return (p)` instead of a `plot(p)`.

![Screenshot from 2019-09-08 17-31-38](https://user-images.githubusercontent.com/1233486/64494060-8d3f3780-d25e-11e9-9651-0c76b9008a07.png)

Or `ols_plot_resid_lev`, is [printing _and_ returning the plot](https://github.com/rsquaredacademy/olsrr/blob/master/R/ols-rstud-vs-lev-plot.R#L75) in a list:

![Screenshot from 2019-09-08 17-34-00](https://user-images.githubusercontent.com/1233486/64494088-dbecd180-d25e-11e9-9f58-68ef0d66db0c.png)

I would add an option that defaults to TRUE, `print_plot = T` to every plot method, so that the current behavior is not altered. What do you think?

**Comment by aravindhebbali** [comment]
Thanks for the suggestion @jmberros . Will do this in the upcoming release.
