### ISSUE TITLE
Best subset regression options

### ISSUE THREAD

**Issue by aravindhebbali** [rsquaredacademy/olsrr#157]
Allow the user to select the criterion in `ols_step_best_subset()`. Currently, it is R2 but the end user cannot specify the criterion.

**Comment by Fernal73** [comment]
Can the user specify multiple criteria with the result being the union of the criteria specified?

**Comment by aravindhebbali** [comment]
Yes.. an option can be given to the user to specify multiple criteria. When you say the union of criteria, if the criteria(s) return model with different set of predictors, the model returned by the function should use the union of those predictors right?

**Comment by Fernal73** [comment]
No, the union of best models for each criteria specified. 

What does the existing functionality provide?

 Additionally, you can add an option to provide a number of best models, not just one.

**Comment by Fernal73** [comment]
> Yes.. an option can be given to the user to specify multiple criteria. When you say the union of criteria, if the criteria(s) return model with different set of predictors, the model returned by the function should use the union of those predictors right?

I don't see why you're asking me this question. It's quite obvious that a union or intersection applies to sets, not to predictors. I've opened a fresh issue --- if that's the issue instead.
