### ISSUE TITLE
ols_step_both_aic doesn't return model

### ISSUE THREAD

**Issue by qwertytam** [rsquaredacademy/olsrr#167]
Hi, when I use `ols_step_both_p` the return includes `model` an object of class `lm`. When I use `ols_step_both_aic`, `model` is not included as a component in contradiction to the documentation. Looking through the source code for both functions, I see that the return `out <- list` statement for `ols_step_both_p` includes `model` on line 336, but `ols_step_both_aic` does not. Is it possible to include `model` for `ols_step_both_aic`? Apologies if I have missed this issue raised elsewhere.

**Comment by aravindhebbali** [comment]
Hi @qwertytam Thanks for bringing this to my attention. Will fix it right away.

**Comment by aravindhebbali** [comment]
I have fixed this in the development version as it will be a while before we update the CRAN version.
