### ISSUE TITLE
Mismatch manual and output in ols_step_all_possible()

### ISSUE THREAD

**Issue by modche** [rsquaredacademy/olsrr#180]
Nice package!

There is a mismatch between the manual of `ols_step_all_possible()` and the output of the function (i.e. column names are not the same.)
I guess `mindex` is the model run and `n` is the number of predictors.

Michael

**Comment by aravindhebbali** [comment]
Yes.. thanks for bringing this to our notice. Will fix it right away.

**Comment by modche** [comment]
Nice. Thanks.
